In [1]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [2]:
# Answer =
import numpy as np
# Create 3x3 array
arr = np.random.randint(1, 101, (3, 3))
# Interchange rows and columns
transposed_arr = arr.T
print("Original Array:\n", arr)
print("Transposed Array:\n", transposed_arr)


Original Array:
 [[20  4 84]
 [19 56  1]
 [50 26 10]]
Transposed Array:
 [[20 19 50]
 [ 4 56 26]
 [84  1 10]]


In [3]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [4]:
# Answer =
arr = np.arange(10)
arr_2x5 = arr.reshape(2, 5)
arr_5x2 = arr.reshape(5, 2)
print("Original Array:\n", arr)
print("2x5 Array:\n", arr_2x5)
print("5x2 Array:\n", arr_5x2)


Original Array:
 [0 1 2 3 4 5 6 7 8 9]
2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [5]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

SyntaxError: invalid decimal literal (<ipython-input-5-afc4079c8c54>, line 1)

In [6]:
# Answer =
arr = np.random.rand(4, 4)
padded_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("Original Array:\n", arr)
print("Array with Border:\n", padded_arr)


Original Array:
 [[0.92871318 0.69396754 0.00662638 0.56455271]
 [0.88769265 0.10486823 0.08423252 0.53186496]
 [0.97346032 0.3053902  0.89061504 0.68626805]
 [0.55406944 0.65413735 0.75915982 0.46232073]]
Array with Border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.92871318 0.69396754 0.00662638 0.56455271 0.        ]
 [0.         0.88769265 0.10486823 0.08423252 0.53186496 0.        ]
 [0.         0.97346032 0.3053902  0.89061504 0.68626805 0.        ]
 [0.         0.55406944 0.65413735 0.75915982 0.46232073 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [7]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.




In [8]:
# Answer =
arr = np.arange(10, 61, 5)
print("Array:", arr)


Array: [10 15 20 25 30 35 40 45 50 55 60]


In [9]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
# (uppercase, lowercase, title case, etc.) to each element.

In [10]:
# Answer =
arr = np.array(['python', 'numpy', 'pandas'])
upper = np.char.upper(arr)
lower = np.char.lower(arr)
title = np.char.title(arr)
print("Uppercase:", upper)
print("Lowercase:", lower)
print("Title Case:", title)


Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']


In [11]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [12]:
# Answer =
arr = np.array(['python', 'numpy', 'pandas'])
spaced = np.char.join(' ', arr)
print("Spaced Words:", spaced)


Spaced Words: ['p y t h o n' 'n u m p y' 'p a n d a s']


In [13]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [14]:
# Answer =
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [15]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [16]:
# Answer =
identity = np.eye(5)
diagonal = np.diag(identity)
print("Identity Matrix:\n", identity)
print("Diagonal Elements:", diagonal)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


In [17]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
# this array


In [18]:
# Answer =
arr = np.random.randint(0, 1001, 100)
# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

primes = arr[np.vectorize(is_prime)(arr)]
print("Original Array:\n", arr)
print("Prime Numbers:\n", primes)


Original Array:
 [853 753 708 761 832 981 947 122 420 399 915 501 982  25 851 255 944 299
  33 197  36 468  88 206 602 745 792 711 919 268 991 481 974 690  47 704
 921 799 679 150 734 664 728 132 190 964 682 238 462 561 382 925 312  97
 972 431 227 365 344 683   9 187 253 562 467 678 998 800 630 191 272 728
 564 636 932 256 191  35 956  20 872 557 808 209 144 878 971 945 289 447
 299  52 148 254 272 671 353 439  38 902]
Prime Numbers:
 [853 761 947 197 919 991  47  97 431 227 683 467 191 191 557 971 353 439]


In [19]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
# averages.


In [ ]:
# Answer =
temperatures = np.random.uniform(20, 35, 30)  # Random temperatures for 30 days
weekly_averages = temperatures.reshape(4, 7).mean(axis=1)
print("Daily Temperatures:\n", temperatures)
print("Weekly Averages:\n", weekly_averages)
